# This is a basic workflow to help you get started with Actions
name: CI - Hosting

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]
    paths:
      - "apps/web-client/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web-client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "apps/web-client/yarn.lock"
      - name: Install Dependencies
        run: yarn install
      - name: Check Prettier
        run: yarn prettier:check
      - name: Check ESLint
        run: yarn eslint:check
      - name: Check Types
        run: yarn type:check
      - name: Build
        run: yarn build
